<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>calendar</name>
   <tag></tag>
   <elementGuidId>a7a123db-6644-4502-9b39-aa5346a74531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@data-id=&quot;checkInDate&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.tvat-calendarContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
